//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuriCorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id { get; set; }
        public string CodigoReserva { get; set; }
        public string FechaReserva { get; set; }
        public int IdCliente { get; set; }
        public int IdVendedor { get; set; }
        public decimal Costo { get; set; }
        public decimal PrecioVenta { get; set; }
        public int IdVehiculoCiudad { get; set; }
        public int IdCiudad { get; set; }
        public int IdPais { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
