//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuriCorAPI.ServiceReferenceReservaVehiculos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultarVehiculosRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultarVehiculosRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraRetiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraDevolucionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCiudad {
            get {
                return this.IdCiudadField;
            }
            set {
                if ((this.IdCiudadField.Equals(value) != true)) {
                    this.IdCiudadField = value;
                    this.RaisePropertyChanged("IdCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime FechaHoraRetiro {
            get {
                return this.FechaHoraRetiroField;
            }
            set {
                if ((this.FechaHoraRetiroField.Equals(value) != true)) {
                    this.FechaHoraRetiroField = value;
                    this.RaisePropertyChanged("FechaHoraRetiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime FechaHoraDevolucion {
            get {
                return this.FechaHoraDevolucionField;
            }
            set {
                if ((this.FechaHoraDevolucionField.Equals(value) != true)) {
                    this.FechaHoraDevolucionField = value;
                    this.RaisePropertyChanged("FechaHoraDevolucion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultarVehiculosDisponiblesResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultarVehiculosDisponiblesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.VehiculoModel[] VehiculosEncontradosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.VehiculoModel[] VehiculosEncontrados {
            get {
                return this.VehiculosEncontradosField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculosEncontradosField, value) != true)) {
                    this.VehiculosEncontradosField = value;
                    this.RaisePropertyChanged("VehiculosEncontrados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoModel", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class VehiculoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadDisponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadPuertasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiudadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioPorDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TieneAireAconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TieneDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VehiculoCiudadIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadDisponible {
            get {
                return this.CantidadDisponibleField;
            }
            set {
                if ((this.CantidadDisponibleField.Equals(value) != true)) {
                    this.CantidadDisponibleField = value;
                    this.RaisePropertyChanged("CantidadDisponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadPuertas {
            get {
                return this.CantidadPuertasField;
            }
            set {
                if ((this.CantidadPuertasField.Equals(value) != true)) {
                    this.CantidadPuertasField = value;
                    this.RaisePropertyChanged("CantidadPuertas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadId {
            get {
                return this.CiudadIdField;
            }
            set {
                if ((this.CiudadIdField.Equals(value) != true)) {
                    this.CiudadIdField = value;
                    this.RaisePropertyChanged("CiudadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioPorDia {
            get {
                return this.PrecioPorDiaField;
            }
            set {
                if ((this.PrecioPorDiaField.Equals(value) != true)) {
                    this.PrecioPorDiaField = value;
                    this.RaisePropertyChanged("PrecioPorDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntajeField, value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TieneAireAcon {
            get {
                return this.TieneAireAconField;
            }
            set {
                if ((this.TieneAireAconField.Equals(value) != true)) {
                    this.TieneAireAconField = value;
                    this.RaisePropertyChanged("TieneAireAcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TieneDireccion {
            get {
                return this.TieneDireccionField;
            }
            set {
                if ((this.TieneDireccionField.Equals(value) != true)) {
                    this.TieneDireccionField = value;
                    this.RaisePropertyChanged("TieneDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCambio {
            get {
                return this.TipoCambioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCambioField, value) != true)) {
                    this.TipoCambioField = value;
                    this.RaisePropertyChanged("TipoCambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehiculoCiudadId {
            get {
                return this.VehiculoCiudadIdField;
            }
            set {
                if ((this.VehiculoCiudadIdField.Equals(value) != true)) {
                    this.VehiculoCiudadIdField = value;
                    this.RaisePropertyChanged("VehiculoCiudadId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.ExceptionHan" +
        "dling")]
    [System.SerializableAttribute()]
    public partial class StatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnerExceptionDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerExceptionDescription {
            get {
                return this.InnerExceptionDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionDescriptionField, value) != true)) {
                    this.InnerExceptionDescriptionField = value;
                    this.RaisePropertyChanged("InnerExceptionDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservarVehiculoRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ReservarVehiculoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoNombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraDevolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraRetiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVehiculoCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.LugarRetiroDevolucion LugarDevolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.LugarRetiroDevolucion LugarRetiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoNombreCliente {
            get {
                return this.ApellidoNombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoNombreClienteField, value) != true)) {
                    this.ApellidoNombreClienteField = value;
                    this.RaisePropertyChanged("ApellidoNombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHoraDevolucion {
            get {
                return this.FechaHoraDevolucionField;
            }
            set {
                if ((this.FechaHoraDevolucionField.Equals(value) != true)) {
                    this.FechaHoraDevolucionField = value;
                    this.RaisePropertyChanged("FechaHoraDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHoraRetiro {
            get {
                return this.FechaHoraRetiroField;
            }
            set {
                if ((this.FechaHoraRetiroField.Equals(value) != true)) {
                    this.FechaHoraRetiroField = value;
                    this.RaisePropertyChanged("FechaHoraRetiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVehiculoCiudad {
            get {
                return this.IdVehiculoCiudadField;
            }
            set {
                if ((this.IdVehiculoCiudadField.Equals(value) != true)) {
                    this.IdVehiculoCiudadField = value;
                    this.RaisePropertyChanged("IdVehiculoCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.LugarRetiroDevolucion LugarDevolucion {
            get {
                return this.LugarDevolucionField;
            }
            set {
                if ((this.LugarDevolucionField.Equals(value) != true)) {
                    this.LugarDevolucionField = value;
                    this.RaisePropertyChanged("LugarDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.LugarRetiroDevolucion LugarRetiro {
            get {
                return this.LugarRetiroField;
            }
            set {
                if ((this.LugarRetiroField.Equals(value) != true)) {
                    this.LugarRetiroField = value;
                    this.RaisePropertyChanged("LugarRetiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumentoCliente {
            get {
                return this.NroDocumentoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoClienteField, value) != true)) {
                    this.NroDocumentoClienteField = value;
                    this.RaisePropertyChanged("NroDocumentoCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LugarRetiroDevolucion", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    public enum LugarRetiroDevolucion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aeropuerto = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TerminalBuses = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hotel = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservarVehiculoResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ReservarVehiculoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.ReservaEntity ReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.ReservaEntity Reserva {
            get {
                return this.ReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservaField, value) != true)) {
                    this.ReservaField = value;
                    this.RaisePropertyChanged("Reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaEntity", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.DataBaseMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class ReservaEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoNombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.EstadoReservaEnum EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraDevolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraRetiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarDevolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarRetiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.VehiculoPorCiudadEntity VehiculoPorCiudadEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VehiculoPorCiudadIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoNombreCliente {
            get {
                return this.ApellidoNombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoNombreClienteField, value) != true)) {
                    this.ApellidoNombreClienteField = value;
                    this.RaisePropertyChanged("ApellidoNombreCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReserva {
            get {
                return this.CodigoReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoReservaField, value) != true)) {
                    this.CodigoReservaField = value;
                    this.RaisePropertyChanged("CodigoReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.EstadoReservaEnum Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCancelacion {
            get {
                return this.FechaCancelacionField;
            }
            set {
                if ((this.FechaCancelacionField.Equals(value) != true)) {
                    this.FechaCancelacionField = value;
                    this.RaisePropertyChanged("FechaCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHoraDevolucion {
            get {
                return this.FechaHoraDevolucionField;
            }
            set {
                if ((this.FechaHoraDevolucionField.Equals(value) != true)) {
                    this.FechaHoraDevolucionField = value;
                    this.RaisePropertyChanged("FechaHoraDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHoraRetiro {
            get {
                return this.FechaHoraRetiroField;
            }
            set {
                if ((this.FechaHoraRetiroField.Equals(value) != true)) {
                    this.FechaHoraRetiroField = value;
                    this.RaisePropertyChanged("FechaHoraRetiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaReserva {
            get {
                return this.FechaReservaField;
            }
            set {
                if ((this.FechaReservaField.Equals(value) != true)) {
                    this.FechaReservaField = value;
                    this.RaisePropertyChanged("FechaReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LugarDevolucion {
            get {
                return this.LugarDevolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarDevolucionField, value) != true)) {
                    this.LugarDevolucionField = value;
                    this.RaisePropertyChanged("LugarDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LugarRetiro {
            get {
                return this.LugarRetiroField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarRetiroField, value) != true)) {
                    this.LugarRetiroField = value;
                    this.RaisePropertyChanged("LugarRetiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumentoCliente {
            get {
                return this.NroDocumentoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoClienteField, value) != true)) {
                    this.NroDocumentoClienteField = value;
                    this.RaisePropertyChanged("NroDocumentoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalReserva {
            get {
                return this.TotalReservaField;
            }
            set {
                if ((this.TotalReservaField.Equals(value) != true)) {
                    this.TotalReservaField = value;
                    this.RaisePropertyChanged("TotalReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCancelacion {
            get {
                return this.UsuarioCancelacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCancelacionField, value) != true)) {
                    this.UsuarioCancelacionField = value;
                    this.RaisePropertyChanged("UsuarioCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioReserva {
            get {
                return this.UsuarioReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioReservaField, value) != true)) {
                    this.UsuarioReservaField = value;
                    this.RaisePropertyChanged("UsuarioReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.VehiculoPorCiudadEntity VehiculoPorCiudadEntity {
            get {
                return this.VehiculoPorCiudadEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculoPorCiudadEntityField, value) != true)) {
                    this.VehiculoPorCiudadEntityField = value;
                    this.RaisePropertyChanged("VehiculoPorCiudadEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehiculoPorCiudadId {
            get {
                return this.VehiculoPorCiudadIdField;
            }
            set {
                if ((this.VehiculoPorCiudadIdField.Equals(value) != true)) {
                    this.VehiculoPorCiudadIdField = value;
                    this.RaisePropertyChanged("VehiculoPorCiudadId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoPorCiudadEntity", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.DataBaseMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class VehiculoPorCiudadEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadDisponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.CiudadEntity CiudadEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiudadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.VehiculoEntity VehiculoEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VehiculoIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadDisponible {
            get {
                return this.CantidadDisponibleField;
            }
            set {
                if ((this.CantidadDisponibleField.Equals(value) != true)) {
                    this.CantidadDisponibleField = value;
                    this.RaisePropertyChanged("CantidadDisponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.CiudadEntity CiudadEntity {
            get {
                return this.CiudadEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadEntityField, value) != true)) {
                    this.CiudadEntityField = value;
                    this.RaisePropertyChanged("CiudadEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadId {
            get {
                return this.CiudadIdField;
            }
            set {
                if ((this.CiudadIdField.Equals(value) != true)) {
                    this.CiudadIdField = value;
                    this.RaisePropertyChanged("CiudadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.VehiculoEntity VehiculoEntity {
            get {
                return this.VehiculoEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiculoEntityField, value) != true)) {
                    this.VehiculoEntityField = value;
                    this.RaisePropertyChanged("VehiculoEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehiculoId {
            get {
                return this.VehiculoIdField;
            }
            set {
                if ((this.VehiculoIdField.Equals(value) != true)) {
                    this.VehiculoIdField = value;
                    this.RaisePropertyChanged("VehiculoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoReservaEnum", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.DataBaseMode" +
        "l")]
    public enum EstadoReservaEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activa = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelada = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CiudadEntity", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.DataBaseMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class CiudadEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.PaisEntity PaisEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaisIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.PaisEntity PaisEntity {
            get {
                return this.PaisEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisEntityField, value) != true)) {
                    this.PaisEntityField = value;
                    this.RaisePropertyChanged("PaisEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaisId {
            get {
                return this.PaisIdField;
            }
            set {
                if ((this.PaisIdField.Equals(value) != true)) {
                    this.PaisIdField = value;
                    this.RaisePropertyChanged("PaisId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehiculoEntity", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.DataBaseMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class VehiculoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadPuertasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioPorDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TieneAireAconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TieneDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCambioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadPuertas {
            get {
                return this.CantidadPuertasField;
            }
            set {
                if ((this.CantidadPuertasField.Equals(value) != true)) {
                    this.CantidadPuertasField = value;
                    this.RaisePropertyChanged("CantidadPuertas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioPorDia {
            get {
                return this.PrecioPorDiaField;
            }
            set {
                if ((this.PrecioPorDiaField.Equals(value) != true)) {
                    this.PrecioPorDiaField = value;
                    this.RaisePropertyChanged("PrecioPorDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntajeField, value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TieneAireAcon {
            get {
                return this.TieneAireAconField;
            }
            set {
                if ((this.TieneAireAconField.Equals(value) != true)) {
                    this.TieneAireAconField = value;
                    this.RaisePropertyChanged("TieneAireAcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TieneDireccion {
            get {
                return this.TieneDireccionField;
            }
            set {
                if ((this.TieneDireccionField.Equals(value) != true)) {
                    this.TieneDireccionField = value;
                    this.RaisePropertyChanged("TieneDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCambio {
            get {
                return this.TipoCambioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCambioField, value) != true)) {
                    this.TipoCambioField = value;
                    this.RaisePropertyChanged("TipoCambio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaisEntity", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.DataBaseMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class PaisEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultarReservasRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultarReservasRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncluirCanceladasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncluirCanceladas {
            get {
                return this.IncluirCanceladasField;
            }
            set {
                if ((this.IncluirCanceladasField.Equals(value) != true)) {
                    this.IncluirCanceladasField = value;
                    this.RaisePropertyChanged("IncluirCanceladas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultarReservasResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultarReservasResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.ReservaEntity[] ReservasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.ReservaEntity[] Reservas {
            get {
                return this.ReservasField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservasField, value) != true)) {
                    this.ReservasField = value;
                    this.RaisePropertyChanged("Reservas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelarReservaRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class CancelarReservaRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoReservaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReserva {
            get {
                return this.CodigoReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoReservaField, value) != true)) {
                    this.CodigoReservaField = value;
                    this.RaisePropertyChanged("CodigoReserva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelarReservaResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class CancelarReservaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.ReservaEntity ReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.ReservaEntity Reserva {
            get {
                return this.ReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservaField, value) != true)) {
                    this.ReservaField = value;
                    this.RaisePropertyChanged("Reserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultarCiudadesRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultarCiudadesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((this.IdPaisField.Equals(value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultarCiudadesResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultarCiudadesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.CiudadEntity[] CiudadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.CiudadEntity[] Ciudades {
            get {
                return this.CiudadesField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadesField, value) != true)) {
                    this.CiudadesField = value;
                    this.RaisePropertyChanged("Ciudades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultarPaisesResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultarPaisesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TuriCorAPI.ServiceReferenceReservaVehiculos.PaisEntity[] PaisesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TuriCorAPI.ServiceReferenceReservaVehiculos.PaisEntity[] Paises {
            get {
                return this.PaisesField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisesField, value) != true)) {
                    this.PaisesField = value;
                    this.RaisePropertyChanged("Paises");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceReservaVehiculos.IWCFReservaVehiculos")]
    public interface IWCFReservaVehiculos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarVehiculosDisponibles", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ConsultarVehiculosDisponiblesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TuriCorAPI.ServiceReferenceReservaVehiculos.StatusResponse), Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarVehiculosDisponiblesStatusRespon" +
            "seFault", Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.ExceptionHan" +
            "dling")]
        TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarVehiculosDisponiblesResponse ConsultarVehiculosDisponibles(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarVehiculosRequest ConsultarVehiculosRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarVehiculosDisponibles", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ConsultarVehiculosDisponiblesResponse")]
        System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarVehiculosDisponiblesResponse> ConsultarVehiculosDisponiblesAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarVehiculosRequest ConsultarVehiculosRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ReservarVehiculo", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ReservarVehiculoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TuriCorAPI.ServiceReferenceReservaVehiculos.StatusResponse), Action="http://tempuri.org/IWCFReservaVehiculos/ReservarVehiculoStatusResponseFault", Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.ExceptionHan" +
            "dling")]
        TuriCorAPI.ServiceReferenceReservaVehiculos.ReservarVehiculoResponse ReservarVehiculo(TuriCorAPI.ServiceReferenceReservaVehiculos.ReservarVehiculoRequest ReservarVehiculoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ReservarVehiculo", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ReservarVehiculoResponse")]
        System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ReservarVehiculoResponse> ReservarVehiculoAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.ReservarVehiculoRequest ReservarVehiculoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarReservas", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ConsultarReservasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TuriCorAPI.ServiceReferenceReservaVehiculos.StatusResponse), Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarReservasStatusResponseFault", Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.ExceptionHan" +
            "dling")]
        TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarReservasResponse ConsultarReservas(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarReservasRequest ConsultarReservasRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarReservas", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ConsultarReservasResponse")]
        System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarReservasResponse> ConsultarReservasAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarReservasRequest ConsultarReservasRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/CancelarReserva", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/CancelarReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TuriCorAPI.ServiceReferenceReservaVehiculos.StatusResponse), Action="http://tempuri.org/IWCFReservaVehiculos/CancelarReservaStatusResponseFault", Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.ExceptionHan" +
            "dling")]
        TuriCorAPI.ServiceReferenceReservaVehiculos.CancelarReservaResponse CancelarReserva(TuriCorAPI.ServiceReferenceReservaVehiculos.CancelarReservaRequest CancelarReservaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/CancelarReserva", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/CancelarReservaResponse")]
        System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.CancelarReservaResponse> CancelarReservaAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.CancelarReservaRequest CancelarReservaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarCiudades", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ConsultarCiudadesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TuriCorAPI.ServiceReferenceReservaVehiculos.StatusResponse), Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarCiudadesStatusResponseFault", Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.ExceptionHan" +
            "dling")]
        TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarCiudadesResponse ConsultarCiudades(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarCiudadesRequest ConsultarCiudadesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarCiudades", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ConsultarCiudadesResponse")]
        System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarCiudadesResponse> ConsultarCiudadesAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarCiudadesRequest ConsultarCiudadesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarPaises", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ConsultarPaisesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TuriCorAPI.ServiceReferenceReservaVehiculos.StatusResponse), Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarPaisesStatusResponseFault", Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFReservaVehiculos.Business.ExceptionHan" +
            "dling")]
        TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarPaisesResponse ConsultarPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFReservaVehiculos/ConsultarPaises", ReplyAction="http://tempuri.org/IWCFReservaVehiculos/ConsultarPaisesResponse")]
        System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarPaisesResponse> ConsultarPaisesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFReservaVehiculosChannel : TuriCorAPI.ServiceReferenceReservaVehiculos.IWCFReservaVehiculos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFReservaVehiculosClient : System.ServiceModel.ClientBase<TuriCorAPI.ServiceReferenceReservaVehiculos.IWCFReservaVehiculos>, TuriCorAPI.ServiceReferenceReservaVehiculos.IWCFReservaVehiculos {
        
        public WCFReservaVehiculosClient() {
        }
        
        public WCFReservaVehiculosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFReservaVehiculosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFReservaVehiculosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFReservaVehiculosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarVehiculosDisponiblesResponse ConsultarVehiculosDisponibles(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarVehiculosRequest ConsultarVehiculosRequest) {
            return base.Channel.ConsultarVehiculosDisponibles(ConsultarVehiculosRequest);
        }
        
        public System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarVehiculosDisponiblesResponse> ConsultarVehiculosDisponiblesAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarVehiculosRequest ConsultarVehiculosRequest) {
            return base.Channel.ConsultarVehiculosDisponiblesAsync(ConsultarVehiculosRequest);
        }
        
        public TuriCorAPI.ServiceReferenceReservaVehiculos.ReservarVehiculoResponse ReservarVehiculo(TuriCorAPI.ServiceReferenceReservaVehiculos.ReservarVehiculoRequest ReservarVehiculoRequest) {
            return base.Channel.ReservarVehiculo(ReservarVehiculoRequest);
        }
        
        public System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ReservarVehiculoResponse> ReservarVehiculoAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.ReservarVehiculoRequest ReservarVehiculoRequest) {
            return base.Channel.ReservarVehiculoAsync(ReservarVehiculoRequest);
        }
        
        public TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarReservasResponse ConsultarReservas(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarReservasRequest ConsultarReservasRequest) {
            return base.Channel.ConsultarReservas(ConsultarReservasRequest);
        }
        
        public System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarReservasResponse> ConsultarReservasAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarReservasRequest ConsultarReservasRequest) {
            return base.Channel.ConsultarReservasAsync(ConsultarReservasRequest);
        }
        
        public TuriCorAPI.ServiceReferenceReservaVehiculos.CancelarReservaResponse CancelarReserva(TuriCorAPI.ServiceReferenceReservaVehiculos.CancelarReservaRequest CancelarReservaRequest) {
            return base.Channel.CancelarReserva(CancelarReservaRequest);
        }
        
        public System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.CancelarReservaResponse> CancelarReservaAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.CancelarReservaRequest CancelarReservaRequest) {
            return base.Channel.CancelarReservaAsync(CancelarReservaRequest);
        }
        
        public TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarCiudadesResponse ConsultarCiudades(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarCiudadesRequest ConsultarCiudadesRequest) {
            return base.Channel.ConsultarCiudades(ConsultarCiudadesRequest);
        }
        
        public System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarCiudadesResponse> ConsultarCiudadesAsync(TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarCiudadesRequest ConsultarCiudadesRequest) {
            return base.Channel.ConsultarCiudadesAsync(ConsultarCiudadesRequest);
        }
        
        public TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarPaisesResponse ConsultarPaises() {
            return base.Channel.ConsultarPaises();
        }
        
        public System.Threading.Tasks.Task<TuriCorAPI.ServiceReferenceReservaVehiculos.ConsultarPaisesResponse> ConsultarPaisesAsync() {
            return base.Channel.ConsultarPaisesAsync();
        }
    }
}
